### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by mshulman** [landonr/homeThing#1]
I don’t see the c++ code in the repo, only header files. 

Where should I look? 

Also, do you have build files checked in?

**Comment by landonr** [comment]
its all in the header files. ill make a pr to move it to cpp files

**Comment by landonr** [comment]
it wouldn't compile :I. my other esphome projects all include .h files only so it might be how its supposed to be

**Comment by mshulman** [comment]
What hardware should I buy to try this?

-ms


On Sep 9, 2022, at 8:12 AM, Lando ***@***.***> wrote:

﻿

it wouldn't compile :I. my other esphome projects all include .h files only so it might be how its supposed to be

**Comment by landonr** [comment]
https://github.com/landonr/esphome-remote/blob/main/GettingStarted.md#what-you-need

An M5Stack Fire is the easiest because it already has a battery and a case. If you end up going with a Lilygo T4 or TDisplay you can add a rotary scrollwheel using the gpio pins

Pretty much any esp32 + display combo with 2+ buttons that works with ESPHome will work for this project

**Comment by LuxStatera** [comment]
Will a D1 mini work?

**Comment by landonr** [comment]
I have one but I don't have an extra display. It should, which display are you using?

**Comment by LuxStatera** [comment]
I have ordered any parts yet since I wanted to see if I would also need to order an ESP32 or if a D1 mini would work since I already have a few extras

**Comment by landonr** [comment]
D1 should work with any display supported by esphome

**Comment by LuxStatera** [comment]
Sounds good I'll order some parts. Any plans for a 3D printed case?

**Comment by landonr** [comment]
yes it's in progress. hopefully just a few weeks

**Comment by LuxStatera** [comment]
You rock!

**Comment by landonr** [comment]
fixed in #41
