### ISSUE TITLE
Problem with order from pcbway.com 

### ISSUE THREAD

**Issue by Shiroe93** [landonr/homeThing#120]
I order the manufacturing of your project from your project page but the sales reps need to know more details about the case such as how to assembly, if it needs threads etc.
Can you please provide me the details or respond to the details request from the rep on pcbway.com directly?
Thank you

**Comment by 11mila** [comment]
Hi i'm mila from PCBWay. We got reply from author. The author said the case shouldn't need threads but it would help. And he is  working on a build quide which should help.

**Comment by landonr** [comment]
https://www.youtube.com/watch?v=hcDLqpd2mt0
