### ISSUE TITLE
Breakout PCB for tdisplay and scrollwheel

### ISSUE THREAD

**Issue by landonr** [landonr/homeThing#21]
Hi @landonr , I made  a breakout PCB for tdisplay and scroolwheel,like this

![image](https://user-images.githubusercontent.com/1695416/200207939-88052315-2b0d-41e0-b662-382fd0ef3e8d.png)
![image](https://user-images.githubusercontent.com/1695416/200207985-f266220c-0b4b-4525-af75-f10a8cba9911.png)
![image](https://user-images.githubusercontent.com/1695416/200208005-72179ae0-f8d5-4003-a1ad-68f14a353ee7.png)

_Originally posted by @goxofy in https://github.com/landonr/esphome-remote/issues/16#issuecomment-1304970234_

**Comment by landonr** [comment]
@goxofy first off this is awesome work, thank you!

How would we connect the battery to the tdisplay? I think we can add a pin on the back of the pcb for vin/ground and include a battery header

**Comment by goxofy** [comment]
I am designing a power mnagement IC for the board in order to charge by the typec on ESP.

**Comment by landonr** [comment]
the tdisplay includes a power manager ic. are you sticking with the tdisplay?

**Comment by goxofy** [comment]
i am trying to change the builtin ic, now the battery charing is inconvenient

**Comment by landonr** [comment]
ah that makes sense. The tdisplay screen is really small. would it make sense to upgrade to a standalone display that's larger like a ILI9341 and use a different esp32 chip?

**Comment by goxofy** [comment]
Or can we add another power ic on the board to charge the battery standalone?

**Comment by landonr** [comment]
which ic are you looking at? it would be nice to have one with an accurate fuel guage

**Comment by goxofy** [comment]
I bought this https://detail.tmall.com/item.htm?id=677456511513&spm=a1z09.2.0.0.4c4f2e8dfx6BFo&_u=f49o7j09dd1 still on the way

**Comment by landonr** [comment]
I cant see that without signing up and I don't understand the language. Can you share a screenshot of the specs?

**Comment by landonr** [comment]
@goxofy can you share the pcb
