### ISSUE TITLE
3d printed case

### ISSUE THREAD

**Issue by landonr** [landonr/homeThing#29]
**Is your feature request related to a problem? Please describe.**
the bare components are too pokey

**Describe the solution you'd like**
a 3d printed case where the components are mounted by screws. The case could have pogo pins to charge easily. 

**Describe alternatives you've considered**
we've considered building the case around a PCB but since the components are basic we can skip that and wire everything together using jumper cables 

**Additional context**
requirements
- fits tdisplay
- fits a lipo
- fits ano rotary controller
- doesn't melt while charging
- passthrough buttons for tdisplays internal buttons
- usbc port hole

**Comment by landonr** [comment]
here's two different concepts from Jasper who posted in Discord

![image](https://user-images.githubusercontent.com/2607659/202439312-5d9d0610-8992-47a8-bdc3-1e8bf3315278.png)
![image](https://user-images.githubusercontent.com/2607659/202439364-cc103751-c579-4889-9f5c-99e5017a1f29.png)

![image](https://user-images.githubusercontent.com/2607659/202439472-57b410a6-b136-4a7d-a041-ff7741fad30b.png)
![image](https://user-images.githubusercontent.com/2607659/202439504-ef2b9faf-3fe7-40d4-9b4c-b567b5f1013f.png)

**Comment by abroooo** [comment]
Great job in designing these case 🎉 
I personally would love to have something small (maybe think of ipod nano or just your protoype with a case around it). Then maybe we don't need pogo pins and just break out the onboard usbc port out?

**Comment by landonr** [comment]
this case is designed around a 2200mah lipo so it's about as small as it could be. I don't think the pogo pins are mandatory so we could make a version with or without at this same size

**Comment by JasperCohen** [comment]
![esp home remote v5](https://user-images.githubusercontent.com/72053634/202806532-050d729e-c7a2-45b1-bd75-41833e11531a.jpg)

This isn't the final case but i think i will be moving forward with some of the aesthetic features, like the front profile and the back shape. I'm still massaging the screen, and the front surface.

**Comment by JasperCohen** [comment]
![image](https://user-images.githubusercontent.com/72053634/202806989-f22ff619-3277-4de7-b1e9-d4352e317a9a.png)
Also, i know its weird placement but i think this could be a decent spot for a pogo connector. I say this because its dead space right now.

**Comment by landonr** [comment]
That looks so good! have you tried printing any prototypes yet? I think for the pogo pin we'd need to make a dock so we can put the pogo pin wherever it works

**Comment by abroooo** [comment]
> this case is designed around a 2200mah lipo so it's about as small as it could be. I don't think the pogo pins are mandatory so we could make a version with or without at this same size

ahh I see, also can see it on @JasperCohen cross section drawing. And seeing the pictures with transparent case it doesn't look that big at all 😄  Great work @JasperCohen 🚀

**Comment by JasperCohen** [comment]
@landonr this is really just the surfacing so the case isn't ready for printing yet, but at this point I'm going to move ahead with this design with only minor tweaks to the screen trim. 

my goal is to get a printable solid design by today!

**Comment by landonr** [comment]
@JasperCohen thanks for adding the reverse engineered parts #32 and for sharing this on discord! 
![image](https://user-images.githubusercontent.com/2607659/202970354-18aaa537-53ee-4213-bc9d-1bfc50dd5dd6.png)
this looks super professional take your time!

**Comment by landonr** [comment]
case is ordered from our new sponsor, PCBWay! 
![image](https://user-images.githubusercontent.com/2607659/235454159-e172cbdc-814a-4f06-96e4-f700ecc5bb3e.png)
