### ISSUE TITLE
Kodi navigation

### ISSUE THREAD

**Issue by abroooo** [landonr/homeThing#31]
**Is your feature request related to a problem? Please describe.**
Support kodi navigation

**Describe the solution you'd like**
We could have a mode which sends all commands to kodi (`rotate left` => `menu down`) to be able to have a basic navigation through kodi.

**Describe alternatives you've considered**
-

**Additional context**
Possible features:
- up/down/left/right
- play/pause/stop
- volume up/down
I think this would only make sense for devices which have a scroll wheel

**Comment by landonr** [comment]
nice idea! I'll try to install Kodi and get this working while I do the LG webOS stuff

**Comment by abroooo** [comment]
Awesome!

**Comment by landonr** [comment]
#41
